server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-damp-cherry-a5798pvi-pooler.us-east-2.aws.neon.tech:5432/desarollo_db?sslmode=require
    username: desarollo_db_owner
    password: npg_umfSx01teTcB
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
